[build]
  publish = "dist"
  command = "npm run build"
  
# Environment variables for build
[build.environment]
  NODE_VERSION = "18"
  # Add your Supabase environment variables here
  # VITE_SUPABASE_URL = "your_supabase_url"
  # VITE_SUPABASE_ANON_KEY = "your_supabase_anon_key"


[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    X-Content-Type-Options = "nosniff"

# Cache images
[[headers]]
  for = "/*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=86400"
    Vary = "Accept-Encoding"

[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "public, max-age=86400"
    Vary = "Accept-Encoding"

[[headers]]
  for = "/*.gif"
  [headers.values]
    Cache-Control = "public, max-age=86400"
    Vary = "Accept-Encoding"

# Cache HTML with shorter duration
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=3600"
    
# Cache JS and CSS with versioning
[[headers]]
  for = "/assets/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    
[[headers]]
  for = "/assets/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"